# Generated by Django 6.0.6 on 2026-06-25 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0002_alter_numerotelefonico_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='numerotelefonico',
            name='operador',
            field=models.CharField(default='Claro', max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='numerotelefonico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
